[[drone]]
id = 1
connected_node_ids = [ 2, 3, 5, 8, 10,]
pdr = 0.05

[[drone]]
id = 2
connected_node_ids = [ 1, 3, 6, 8, 10, 21, 31,]
pdr = 0.05

[[drone]]
id = 3
connected_node_ids = [ 1, 2, 4, 5, 6, 7, 10,]
pdr = 0.05

[[drone]]
id = 4
connected_node_ids = [ 3, 5, 10,]
pdr = 0.05

[[drone]]
id = 5
connected_node_ids = [ 1, 3, 4, 6, 8,]
pdr = 0.05

[[drone]]
id = 6
connected_node_ids = [ 2, 3, 5, 7, 8, 9, 31,]
pdr = 0.05

[[drone]]
id = 7
connected_node_ids = [ 3, 6, 8, 9,]
pdr = 0.05

[[drone]]
id = 8
connected_node_ids = [ 1, 2, 5, 6, 7, 9, 10,]
pdr = 0.05

[[drone]]
id = 9
connected_node_ids = [ 6, 7, 8, 10,]
pdr = 0.05

[[drone]]
id = 10
connected_node_ids = [ 1, 2, 3, 4, 8, 9,]
pdr = 0.05

[[client]]
id = 21
connected_drone_ids = [ 2,]

[[server]]
id = 31
connected_drone_ids = [ 2, 6,]

