[[drone]]
id = 1
connected_node_ids = [2,6,21]
pdr = 0.05

[[drone]]
id = 2
connected_node_ids = [1,3]
pdr = 0.05

[[drone]]
id = 3
connected_node_ids = [2,6,22]
pdr = 0.05

[[drone]]
id = 6
connected_node_ids = [1,3,31]
pdr = 0.05

[[client]]
id = 21
connected_drone_ids = [1]

[[client]]
id = 22
connected_drone_ids = [3]

[[server]]
id = 31
connected_drone_ids = [6]

