[[drone]]
id = 1
connected_node_ids = [21,22,31]
pdr = 0.00

[[client]]
id = 21
connected_drone_ids = [1]

[[server]]
id = 22
connected_drone_ids = [1]

[[server]]
id = 31
connected_drone_ids = [1]

