[[drone]]
id = 1
connected_node_ids = [ 2, 3, 7, 8, 9, 10,]
pdr = 0.05

[[drone]]
id = 2
connected_node_ids = [ 1, 3, 5, 7, 8, 9, 31,]
pdr = 0.05

[[drone]]
id = 3
connected_node_ids = [ 1, 2, 4, 6, 7, 10, 31,]
pdr = 0.05

[[drone]]
id = 4
connected_node_ids = [ 3, 5, 6, 8,]
pdr = 0.05

[[drone]]
id = 5
connected_node_ids = [ 2, 4, 6, 8, 10,]
pdr = 0.05

[[drone]]
id = 6
connected_node_ids = [ 3, 4, 5, 7,]
pdr = 0.05

[[drone]]
id = 7
connected_node_ids = [ 1, 2, 3, 6, 8, 10,]
pdr = 0.05

[[drone]]
id = 8
connected_node_ids = [ 1, 2, 4, 5, 7, 9, 10,22,]
pdr = 0.05

[[drone]]
id = 9
connected_node_ids = [ 1, 2, 8, 10,]
pdr = 0.05

[[drone]]
id = 10
connected_node_ids = [ 1, 3, 5, 7, 8, 9, 21,]
pdr = 0.05

[[client]]
id = 21
connected_drone_ids = [ 10,]

[[client]]
id = 22
connected_drone_ids = [ 8,]

[[server]]
id = 31
connected_drone_ids = [ 2, 3,]

