[[drone]]
id = 1
connected_node_ids = [ 4, 5, 6, 7,]
pdr = 0.05

[[drone]]
id = 2
connected_node_ids = [ 3, 4, 5, 6, 8,]
pdr = 0.05

[[drone]]
id = 3
connected_node_ids = [ 2, 7, 8, 10,]
pdr = 0.05

[[drone]]
id = 4
connected_node_ids = [ 1, 2, 6, 10,]
pdr = 0.05

[[drone]]
id = 5
connected_node_ids = [ 1, 2, 8, 10,]
pdr = 0.05

[[drone]]
id = 6
connected_node_ids = [ 1, 2, 4, 7, 9,]
pdr = 0.05

[[drone]]
id = 7
connected_node_ids = [ 1, 3, 6, 9, 10,]
pdr = 0.05

[[drone]]
id = 8
connected_node_ids = [ 2, 3, 5, 10,]
pdr = 0.05

[[drone]]
id = 9
connected_node_ids = [ 6, 7, 10,]
pdr = 0.05

[[drone]]
id = 10
connected_node_ids = [ 3, 4, 5, 7, 8, 9,]
pdr = 0.05

[[client]]
id = 39
connected_drone_ids = [ 9, 8,]

[[client]]
id = 40
connected_drone_ids = [ 5, 9,]

[[server]]
id = 49
connected_drone_ids = [ 5, 7,]

[[server]]
id = 50
connected_drone_ids = [ 5, 7,]

